### ISSUE TITLE
An error found

### ISSUE THREAD

**Issue by DamnTricker996** [weninsjtu/guessnumber#1]
The program has a failure to report the correctness of the guess, which the producer has been informed of.

**Comment by weninsjtu** [comment]
ok,I have changed my code,thank you for finding the mistake.

**Comment by sunshin15** [comment]
Let me water one water...
(So concise! Only 58 lines....)

**Comment by dry999** [comment]
It 's concise..very good  I think that it can be better if you can check the input type.
